### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#363]
I have found a fundamental design problem in Java that prevents Aya from being further developed. The pattern matching support is incomplete, and is less powerful than the semantics offered by Rust.

Apart from that, Rust generates smaller binaries and uses less memory, so I propose rewriting Aya in Rust.

P.S. Rust already has a pretty printing library similar to ours (the one implemented by Kiva).

**Comment by imkiva** [comment]
> I have found a fundamental design problem in Java that prevents Aya from being further developed.

What's the problem?

**Comment by imkiva** [comment]
Recently I code in Rust a lot, but I still don't agree to rewrite in Rust. Rust has incomplete and less powerful IDE features:
- the debugger's _evaluate expression_ is likely broken for complex expressions.
- the latency of code analysis on-the-fly is comparingly *much* higher than Java
- the type error reporting location generated by CLion is less helpful. It just brutely underlines the whole match instead of telling you the offending match arm.
- When there're two files containing errors, only randomly one file's errors will be displayed in the editor. It's annoying.

And there are also library deficient:
- Using Rust's networking library results in lots of boilerplate error handling code (especially inside lambda's), which is harder to use than Java's.
- Rust does not have a good enough terminal library compared to `jline3`.
- `Rust already has a pretty-printing library similar to ours`, probably we don't (

**Comment by ice1000** [comment]
> Recently I code in Rust a lot, but I still don't agree to rewrite in Rust. Rust has incomplete and less powerful IDE features:
> - the debugger's _evaluate expression_ is likely broken for complex expressions. We will lose the ability of debugger-oriented programming (the whole LSP was written in this way).
> - the conditional breakpoint always causes SIGSEGV in my project, which means, you must write `if <your-condition> { println!("HIT"); }` and set the breakpoint to `println!` to make the breakpoint conditional.
> - the latency of code analysis on-the-fly is comparingly *much* higher than Java, which is far beyond my tolerance.
> - the type error reporting location generated by CLion is less helpful. It just brutely underlines the whole match instead of telling you the offending match arm.
> - When there're two files containing errors, only randomly one file's errors will be displayed in the editor. It's annoying.
> 
> And there are also library deficient:
> - Using Rust's networking library results in lots of boilerplate error handling code (especially inside lambda's), which is harder to use than Java's.
> - Rust does not have a good enough terminal library compared to `jline3`.
> - `Rust already has a pretty-printing library similar to ours`, probably we don't (

Happy holiday! I really appreciate your reply (I learned from it ngl) but unfortunately this ticket is but a joke. We're good.

**Comment by ice1000** [comment]
holiday → April fools

**Comment by ice1000** [comment]
Related: https://github.com/aya-prover/aya-prover-proto/issues/375

**Comment by sequencer** [comment]
why not Scala3

**Comment by wsx-ucb** [comment]
You had me in the first half, not gonna lie.

**Comment by ice1000** [comment]
Btw @imkiva wdym by "probably we don't"? Did you mean Rust doesn't have a good enough pp library or your library is not good enough?

I was talking about a third party library, not the built-in `Display`

**Comment by imkiva** [comment]
呜呜呜呜呜呜呜呜

![image](https://user-images.githubusercontent.com/9902643/161214892-9fe9ef5b-afa1-44bb-a41e-66029ffab249.png)

**Comment by imkiva** [comment]
> Rust doesn't have a good enough pp library
Yes.

> or your library is not good enough?
I don't even remember I once made a pretty library in Rust 😕

**Comment by ice1000** [comment]
@imkiva Let me clarify:

You have made a great one in Java. There exists a third party implementation in Rust.

**Comment by imkiva** [comment]
Oh. I was fooled the second time
