### ISSUE TITLE
Reconsider identifiers

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#563]
Is it _really_ a good idea to have _that_ freedom on identifiers (`ID`)?

Some identifiers that I believe are good to have:

+ `abc`, `name1` and such (C-style) should be ID (Latin, Arabic digits)
+ `sin²` should be valid (mix Latin with unicode Arabic digits)
+ `αθηνα` should be valid (Greek)
+ `ΩS¹`, `sinβ` should be a valid (mix Greek with Latin and unicode digits)
+ `+`, `/`, `-`, `*` should be valid (operators) but we may reserve a few as keywords like `@` (like Java), `#` (?) or `%` (like Idris)
+ `⁄`, `⌀`, `⁒`, `·`, `÷` should be valid (unicode operators)
+ `::`, `:<`, `>>=` are valid (several operators)
+ `+₁`, `+₂`, `÷₂`, `*‘` should be valid (operators followed by unicode digits)

Something that are currently ID, I think are confusing:

+ `+1` -- looks like `λx. x + 1`. Similarly `1+`
+ `call/cc` looks like `call / cc` to people w/o scheme experience. We may call similar function `callCC`, `shiftReset`
+ `suc-suc` -- because we know `suc` is not a "number" so we know it's not `suc - suc`, but if it's `o-o`, it's less clear. It can be `o - o`.
+ `a+b` -- even worse.
+ `a+b=c` -- also valid in Agda. EVEN worse.
+ `+-comm` -- commonly used in Agda. In Idris it's called `plusCommutative` iirc. I think the Idris name is acceptable. I'm not sure though.

I am thinking about a criterion that is similar to Haskell:

+ Let `\a` denote Latin/Greek/CJK/Russian alphabets
+ Let `\o` denote operators (unicode inclusive)
+ Let `\u` denote unicode superscript and subscript (numeric and alphabetic)
+ Let `\d` denote digits (unicode inclusive, exclude super/subscript)

Then `\a[\a\d]*\u* | \o+\u*` basically describes what I wanted. This will cause some renaming in the current stdlib.

**Comment by ice1000** [comment]
By that, we may have shorter expressions like `a+b` like in Haskell

**Comment by ice1000** [comment]
Any idea?

**Comment by wsx-ucb** [comment]
I think as long as we disallow white-spaces in identifiers, I'm totally fine :D
If in addition we enforce white-space *in between* identifiers, then having the current naming freedom also induce no ambiguity (and arguably still easy to parse by human).
While probably it is better to use `addComm` over `a+b=b+a`, naming proof terms of more complicated relation with the white-space collapsing, symbolic style can be easier and clearer in some situations.
Naming things is already hard enough for us programmers, and I think having a wider range of naming style to choose can help alleviate the burden a bit.

**Comment by anqurvanillapy** [comment]
The grammar for identifiers you just mentioned looks cool to me. I always love laying limitations to the surface syntax, as long as it won't bring so much burden and extra mental models to the end users. My principle is making "conventions/specifications" work without any external tools, like linters.

My misc preferences:

* `call/cc`: cooltt endorses this too, but I don't
* `+-comm`: I don't like `plusComm` because it doesn't distinguish "plus" and `+` (unless like Python we know `+` is `__add__`), maybe `commOf+`? Not sure about this either

**Comment by ice1000** [comment]
> The grammar for identifiers you just mentioned looks cool to me. I always love laying limitations to the surface syntax, as long as it won't bring so much burden and extra mental models to the end users. My principle is making "conventions/specifications" work without any external tools, like linters.
> 
> My misc preferences:
> 
> * `call/cc`: cooltt endorses this too, but I don't
> * `+-comm`: I don't like `plusComm` because it doesn't distinguish "plus" and `+` (unless like Python we know `+` is `__add__`), maybe `commOf+`? Not sure about this either

Thank you!

Eventually you'll end up putting all those properties into classes like CommutativeSemiring or TotalOrder or something like that. I think there will be one name that rules them all, and it won't matter much because you won't be proving `+-comm` by using its name -- instead you'll use `solveRing` or `lia` or something

**Comment by imkiva** [comment]
In general, I am fine with current identifiers, that is, composing IDs from a sequence of visually visible characters. 
I don't like putting restrictions on identifiers (because remembering these rules is also a burden to users) except those that _significantly_ improve readability:
- no whitespaces inside (like mixfix operators) 
- no leading numbers (looks like literal suffixes in other languages: `114514ULL`)

And there are other reasons:
- `+-comm` looks better than `plusComm` because for humans, splitting by the hyphen `-` is easier than splitting by any upper-case alphabet. I know you can choose `plus_comm` but the underlines are less beautiful -- they are not centered.
- IDs like `a+b=c`, `+1` and `a+b=b+a` do not actually make code harder to understand. Because the formatter always produce `a + b = b + a` if it is really an expression.

**Comment by ice1000** [comment]
Fair. Closing.
